import Head from 'next/head';
import { Footer, Header } from '@/shared/components';
import Image from 'next/image';

const Pokemon = ({ data }: any) => {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Next Pokemon | {data?.name}</title>
      </Head>
      <Header />
      <main className="bg-[#D9D9D9] ">
        <section className="my-3 mx-auto max-w-7xl">
          <h2 className="mb-10 mt-9 w-full text-center text-4xl md:text-5xl">
            {data?.name}
          </h2>
          <div className="grid grid-cols-1 gap-5 md:grid-cols-2">
            <div className="relative">
              <Image
                src={data?.sprites.other['official-artwork'].front_default}
                alt="pokemon"
                width={300}
                height={300}
                quality={60}
                className="aspect-square w-full scale-75"
              />
            </div>
            <div className="flex h-full w-full flex-col gap-10 px-5 md:mx-0 md:justify-center">
              <div className="w-fit rounded-lg bg-slate-700 p-6 text-white">
                {data?.stats.map((stat: any, index: any) => (
                  <div className="flex justify-between gap-7" key={index}>
                    <p className="">{stat.stat.name}:</p>
                    <p>{stat.base_stat}</p>
                  </div>
                ))}
              </div>
              <div className="w-fit rounded-lg bg-slate-700 p-6 text-white">
                <div className="flex gap-2 ">
                  <h3 className="text-cyan-300">abilities: </h3>
                  {data?.abilities.map((item: any, index: any) => (
                    <p key={index}>{item.ability.name}</p>
                  ))}
                </div>
                <div className="flex gap-2 ">
                  <h3 className="text-violet-300">types: </h3>
                  {data?.types.map((item: any, index: any) => (
                    <p key={index}>{item.type.name}</p>
                  ))}
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <Footer />
    </>
  );
};

export default Pokemon;

export async function getServerSideProps(context: any) {
  const { id } = context.query; // Get the id parameter from the query string

  // Fetch data from external API
  const res = await fetch(`https://pokeapi.co/api/v2/pokemon/${id}`);
  const data = await res.json();

  // Pass data to the page via props
  return { props: { data } };
}
