import Head from 'next/head';
import { Header, Footer } from '../../shared/components/index';
// import Image from 'next/image';
// import { Inter } from 'next/font/google';

// const inter = Inter({ subsets: ['latin'] });

export default function Home(props: any) {
  const { data } = props;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <title>Next Movie | Home page </title>
      </Head>
      <Header />
      <main>
        <pre>{JSON.stringify(data, null, 2)}</pre>
      </main>
      <Footer />
    </>
  );
}
